#systemTenant: "system"

systemTenantUser: "root"

systemTenantPassword: "gc53ovIr44Tq"

#applicationId: 4

#tenant: "customer1"

tenantUser: "user"

tenantPassword: "57vOfhGT5YV"

severity: "INFO"

customeventType: "NewApp"

eventType: "CUSTOM"

test: "Test"

appFile: "src/main/resources/apps.json"

controller: "https://always.appd.duckdns.org:443"
