#systemTenant: "system"

systemTenantUser: ""

systemTenantPassword: ""

#applicationId: 4

#tenant: "customer1"

tenantUser: ""

tenantPassword: ""

severity: "INFO"

customeventType: "NewApp"

eventType: "CUSTOM"

appFile: "./apps.json"

controller: "http(s)://<CONTROLLER_HOST>:<CONTROLLER_PORT>"
